name: LagLens CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install uv
      run: |
        pip install uv
    - name: Install dependencies
      run: |
        uv install
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/
    - name: Run tests
      run: |
        python -m unittest discover -s src/tests
